import * as esbuild from 'esbuild';
import fs from 'fs';
const entry = process.argv.find((a) => a.endsWith('.js') && a.includes('src/')) || 'src/main.js';
const outName = entry === 'src/main.js' ? 'dist/index.html' : 'dist/' + entry.split('/').pop().replace('.js', '.html');
const r = await esbuild.build({ entryPoints: [entry], loader: { '.glb': 'binary', '.jpg': 'binary' }, bundle: true, format: 'iife', minify: process.argv.includes('--min'), write: false, target: 'es2020', legalComments: 'none' });
let js = r.outputFiles[0].text.replace(/<\/script/gi, '<\\/script');
const html = fs.readFileSync('template.html', 'utf8').replace('<script>/*BUNDLE*/</script>', () => '<script>' + js + '</script>');
fs.mkdirSync('dist', { recursive: true });
fs.writeFileSync(outName, html);
console.log('built', (html.length / 1024 / 1024).toFixed(2), 'MB');
